package migrations

import (
	"github.com/flashbots/go-template/database/vars"
	migrate "github.com/rubenv/sql-migrate"
)

var Migration001InitDatabase = &migrate.Migration{
	Id: "001-init-database",
	Up: []string{`
		CREATE TABLE IF NOT EXISTS ` + vars.TableTest + ` (
			id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			inserted_at timestamp NOT NULL default current_timestamp
		);
	`},
	Down: []string{`
		DROP TABLE IF EXISTS ` + vars.TableTest + `;
	`},
	DisableTransactionUp:   false,
	DisableTransactionDown: false,
}
